import React, { useEffect, useState } from 'react';

interface VerifyState {
  ref: string | null;
  company: string | null;
}

const statusBadgeClass =
  'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-100 text-emerald-700';

export default function VerifyGoodStandingPage() {
  const [data, setData] = useState<VerifyState>({ ref: null, company: null });
  const [hasParams, setHasParams] = useState<boolean>(false);

  useEffect(() => {
    try {
      const search = new URLSearchParams(window.location.search);
      const ref = search.get('ref');
      const company = search.get('company');
      setData({ ref, company });
      setHasParams(!!ref || !!company);
    } catch {
      setHasParams(false);
    }
  }, []);

  const { ref, company } = data;

  const showInvalid = !hasParams || !ref;

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 flex items-center justify-center px-4">
      <div className="max-w-xl w-full">
        <div className="mb-4 text-center">
          <div className="text-xs tracking-[0.2em] uppercase text-slate-500">
            Quantilytix (Qx)
          </div>
          <h1 className="mt-2 text-2xl font-semibold tracking-tight">
            Letter of Good Standing Verification
          </h1>
        </div>

        <div className="bg-white shadow-sm rounded-2xl border border-slate-200 p-5 sm:p-6">
          {showInvalid ? (
            <>
              <p className="text-sm text-slate-600">
                This verification link is missing required information or is not
                valid.
              </p>
              <ul className="mt-3 text-xs text-slate-500 list-disc list-inside space-y-1">
                <li>The link should include a <code>?ref=LOGS-...</code> query parameter.</li>
                <li>Please scan the QR code again or request a new letter.</li>
              </ul>
            </>
          ) : (
            <>
              <div className="flex items-center justify-between gap-2 mb-4">
                <span className={statusBadgeClass}>
                  ✅ Generated by Quantilytix platform
                </span>
                <span className="text-[11px] text-slate-500">
                  Reference: <span className="font-mono">{ref}</span>
                </span>
              </div>

              <div className="space-y-3 text-sm">
                {company && (
                  <div className="flex justify-between gap-4">
                    <span className="text-slate-500">Company</span>
                    <span className="font-medium text-right">
                      {decodeURIComponent(company)}
                    </span>
                  </div>
                )}

                <div className="flex justify-between gap-4">
                  <span className="text-slate-500">Reference</span>
                  <span className="font-mono text-right">{ref}</span>
                </div>
              </div>

              <div className="mt-5 border-t border-dashed border-slate-200 pt-4 text-xs text-slate-500 space-y-2">
                <p>
                  This page confirms that the QR code and reference number match
                  a letter of good standing that was generated using the
                  Quantilytix (Qx) accounting platform.
                </p>
                <p>
                  Final validity and acceptance remain subject to the
                  responsible accountant&apos;s signature or approved digital
                  endorsement on the letter itself.
                </p>
                <p>
                  If you require further confirmation, please contact the
                  accountant listed on the letter and quote the reference{' '}
                  <span className="font-mono">{ref}</span>.
                </p>
              </div>
            </>
          )}
        </div>

        <p className="mt-4 text-[11px] text-center text-slate-400">
          © {new Date().getFullYear()} Quantilytix. All rights reserved.
        </p>
      </div>
    </div>
  );
}
